---
title: "Practical Machine Learning Project"
author: "Galen Johnson"
date: "September 26, 2015"
output: html_document
---

##Introduction/Exec Summary
Text text text

## Preparing Data
```{r}
library(caret)
LoadTest <- read.csv("pml-testing.csv",na.strings=c("NA",""))
LoadTrain <- read.csv("pml-training.csv",na.strings=c("NA",""))
NAs <- apply(LoadTrain,2,function(x) {sum(is.na(x))}) 
cleanTrain <- LoadTrain[,which(NAs == 0)]
cleanTest <- LoadTest[,which(NAs == 0)]

```

## Training and Cross Validation
```{r}
trainIndex <- createDataPartition(y = cleanTrain$classe, p=0.7,list=FALSE)
trainSet <- cleanTrain[trainIndex,]
crossValidationSet <- cleanTrain[-trainIndex,]
removeIndex <- as.integer(c(1,2,3,4,5,6))
trainSet <- trainSet[,-removeIndex]
testSet <- cleanTest[,-removeIndex]
```

```{r}
mytrControl = trainControl(method = "cv", number = 4)
modelFit <- train(trainSet$classe ~.,data = trainSet, method="rf", trControl = mytrControl)
modelFit
```

```{r}
predicted <- predict(modelFit, crossValidationSet)
SampleError <- sum(predicted == crossValidationSet$classe)/nrow(crossValidationSet)
```

## Project Submission
```{r}
answers <- predict(modelFit, testSet)
```